version: "3"

services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
      container_name: elasticsearch
      environment:
          - discovery.type=single-node
      volumes:
          - esdata:/usr/share/elasticsearch/data
      ports:
          - 9200:9200
      networks:
          - elastic
      labels:
          - co.elastic.logs/module=elasticsearch
          - co.elastic.metrics/module=elasticsearch
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
        - 8000:8000
    networks:
        - elastic

volumes:
  esdata:
    driver: local
networks:
    elastic:
      driver: bridge  